Improved the cloudformation

diff --git a/aws-ec2-loadbalancer/ec2-autohealing-loadbalancer.yml b/aws-ec2-loadbalancer/ec2-autohealing-loadbalancer.yml
--- a/aws-ec2-loadbalancer/ec2-autohealing-loadbalancer.yml
+++ b/aws-ec2-loadbalancer/ec2-autohealing-loadbalancer.yml
@@ -37,7 +37,7 @@ Parameters:
     Description: S3 bucket where application binary is stored (test-zyvika-deployments/zyvika-deployments)
   ApplicationBinary:
     Type: 'String'
-    Default: hello-world-springboot-0.0.1-SNAPSHOT-b0906230455.zip
+    Default: hello-world-springboot-0.0.1-SNAPSHOT-b0906230555.zip
     Description: Application binary with scripts folder containing run.sh and cleanup.sh.
 Resources:
   VPC:
@@ -251,77 +251,49 @@ Resources:
               awslogs: []
           files:
             /etc/cfn/cfn-hup.conf:
-              content: !Join
-                - ''
-                - - |
-                    [main]
-                  - stack=
-                  - !Ref 'AWS::StackId'
-                  - |+
-
-                  - region=
-                  - !Ref 'AWS::Region'
-                  - |+
-
-                  - |
-                    interval=5
-                    verbose=true
+              content: !Sub |
+                [main]
+                stack=${AWS::StackId}
+                region=${AWS::Region}
+                interval=2
+                verbose=true
               mode: '000400'
               owner: root
               group: root
+            # The user actions that the cfn-hup daemon calls periodically are defined in the hooks.conf configuration file.
+            # To support composition of several applications deploying change notification hooks, cfn-hup supports a directory named hooks.d that is
+            # located in the hooks configuration directory. You can place one or more additional hooks configuration files in the hooks.d directory.
+            # The additional hooks files must use the same layout as the hooks.conf file.
             /etc/cfn/hooks.d/cfn-auto-reloader.conf:
-              content: !Join
-                - ''
-                - - |
-                    [cfn-auto-reloader-hook]
-                  - |
-                    triggers=post.add,post.update,post.remove
-                  - >
-                    path=Resources.LaunchTemplate.Metadata.AWS::CloudFormation::Init
-                  - 'action=/opt/aws/bin/cfn-init -v '
-                  - '         --stack '
-                  - !Ref 'AWS::StackName'
-                  - '         --resource LaunchTemplate '
-                  - '         --configsets InstallAndRun '
-                  - '         --region '
-                  - !Ref 'AWS::Region'
-                  - |+
-
-                  - |
-                    runas=root
+              content: !Sub |
+                [cfn-auto-reloader-hook]
+                triggers=post.update
+                path=Resources.LaunchTemplate.Metadata.AWS::CloudFormation::Init
+                action=/opt/aws/bin/cfn-init --verbose --stack ${AWS::StackId} --resource LaunchTemplate --configsets InstallAndRun --region ${AWS::Region}
+                runas=root
               mode: '000400'
               owner: root
               group: root
             /etc/awslogs/awscli.conf:
-              content: !Join
-                - ''
-                - - |
-                    [plugins]
-                    cwlogs = cwlogs
-                    [default]
-                  - region=
-                  - !Ref 'AWS::Region'
-                  - |+
+              content: !Sub |
+                [plugins]
+                cwlogs = cwlogs
+                [default]
+                region=${AWS::Region}
               mode: '000400'
               owner: root
               group: root
             /etc/awslogs/awslogs.conf:
-              content: !Join
-                - ''
-                - - |
-                    [general]
-                    state_file = /var/lib/awslogs/agent-state
-                  - |+
-
-                  - |                    
-                    [/zyvika/app/logs]
-                    datetime_format = %b %d %H:%M:%S
-                    file = /logs/application.log
-                    buffer_duration = 5000
-                    log_stream_name = {instance_id}
-                    initial_position = start_of_file
-                    log_group_name = /zyvika/app/logs
-                  - |+
+              content: !Sub |
+                [general]
+                state_file = /var/lib/awslogs/agent-state
+                [/zyvika/app/logs]
+                datetime_format = %b %d %H:%M:%S
+                file = /logs/application.log
+                buffer_duration = 5000
+                log_stream_name = {instance_id}
+                initial_position = start_of_file
+                log_group_name = /zyvika/app/logs
           services:
             sysvinit:
               cfn-hup:
@@ -360,34 +332,18 @@ Resources:
           - !Ref EC2SecurityGroup
         IamInstanceProfile:
           Arn: !GetAtt ApplicationInstanceProfile.Arn
-        UserData: !Base64
-          'Fn::Join':
-            - ''
-            - - |
-                #!/bin/bash -xe
-              - |
-                yum update -y aws-cfn-bootstrap
-              - |
-                # Install the files and packages from the metadata
-              - '/opt/aws/bin/cfn-init -v '
-              - '         --stack '
-              - !Ref 'AWS::StackName'
-              - '         --resource LaunchTemplate '
-              - '         --configsets InstallAndRun '
-              - '         --region '
-              - !Ref 'AWS::Region'
-              - |+
-
-              - |
-                # Signal the status from cfn-init
-              - '/opt/aws/bin/cfn-signal -e $? '
-              - '         --stack '
-              - !Ref 'AWS::StackName'
-              - '         --resource LaunchTemplate '
-              - '         --region '
-              - !Ref 'AWS::Region'
-              - |+   
-
+        UserData:
+          "Fn::Base64":
+            !Sub |
+            #!/bin/bash -xe
+            # Get the latest CloudFormation package
+            yum update -y aws-cfn-bootstrap
+            # Start cfn-init
+            /opt/aws/bin/cfn-init --verbose --stack ${AWS::StackId} --resource LaunchTemplate --configsets InstallAndRun --region ${AWS::Region} || echo 'Failed to run cfn-init'
+            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
+            service cfn-hup restart || echo 'Failed to restart cfn-hup'
+            # All done so signal success
+            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource LaunchTemplate --region ${AWS::Region}
     CreationPolicy:
       ResourceSignal:
         Timeout: PT5M
